# SPRING APPLICATION
spring.application.name=organizacao.evento
server.port=8080

# MONGODB CONNECTION
spring.data.mongodb.uri=mongodb://localhost:27017/eventos_db
spring.data.mongodb.auto-index-creation=true

# LOGGING
logging.level.root=INFO
logging.level.org.springframework.web=INFO
logging.level.org.springframework.data.mongodb=ERROR

# JACKSON (JSON)
spring.jackson.default-property-inclusion=non_null
spring.jackson.serialization.indent_output=true